version: "3.9"
services:
  # dsbot:
  #   build: .
  #   ports:
  #     - 5000:5000

  rasa:
    image: rasa/rasa:2.8.6-full
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
    command: >
      run
      --enable-api
      -m models/nlu-20210929-081055.tar.gz