version: "3.9"
services:
  # dsbot:
  #   build: .
  #   ports:
  #     - 5000:5000

  rasa:
    image: rasa/rasa:2.8.6-full
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
    command: >
      run
      --enable-api
      -m models/nlu-20210930-135350.tar.gz

  # rasa-train:
  #   image: ubuntu:latest
  #   volumes:
  #     - ./rasa:/app
  #   tty: true