version: "3.9"
services:
  trainer:
    image: rasa/rasa:2.8.6-full
    volumes:
      - ./rasa2:/app
    command: >
      train nlu --fixed-model-name nlu-rasa
  rasa:
    image: rasa/rasa:2.8.6-full
    ports:
      - 5005:5005
    volumes:
      - ./rasa2:/app
    command: >
      run
      --enable-api
      -m 'models/nlu-rasa.tar.gz'